'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const corePolicy=require('../src/codex-safe-core/policy');
const{POLICY_FILE,POLICY_SCHEMA_VERSION,mergePolicy,resolveEffectiveConfig}=require('../src/policy');

test('Change Safe consumes the canonical Core repository policy',()=>{assert.equal(POLICY_FILE,'.codex-safe.json');assert.equal(POLICY_SCHEMA_VERSION,4);assert.equal(POLICY_FILE,corePolicy.POLICY_FILE);assert.equal(POLICY_SCHEMA_VERSION,corePolicy.POLICY_SCHEMA_VERSION);});
test('committed policy can only be tightened locally, never weakened',()=>{const committed={...corePolicy.validatePolicySection('change',{requiredChecks:['build'],requiredApprovals:2,provenancePolicy:'require-review',blockOnReviewFindings:true,requireCleanWorktree:true}),__present:true,__fingerprint:'a'.repeat(64)};const effective=mergePolicy({requiredChecks:['lint'],requiredApprovals:1,provenancePolicy:'require-commit',blockOnReviewFindings:false,requireCleanWorktree:false},committed);assert.deepEqual(effective.requiredChecks,['build','lint']);assert.equal(effective.requiredApprovals,2);assert.equal(effective.provenancePolicy,'require-all');assert.equal(effective.blockOnReviewFindings,true);assert.equal(effective.requireCleanWorktree,true);assert.equal(effective.policySource,'committed+local-tightening');assert.equal(effective.policyFingerprint,'a'.repeat(64));});
test('Core validation fails closed for old schema, unknown fields and wrong types',()=>{assert.throws(()=>corePolicy.parsePolicyDocument('{"schemaVersion":3,"change":{}}'),/schemaVersion/);assert.throws(()=>corePolicy.parsePolicyDocument('{"schemaVersion":4,"change":{"magic":true}}'),/unsupported fields/);assert.throws(()=>corePolicy.parsePolicyDocument('{"schemaVersion":4,"change":{"requirePushedHead":"false"}}'),/boolean/);assert.throws(()=>corePolicy.parsePolicyDocument('{"schemaVersion":4,"change":{"requiredChecks":"build"}}'),/array/);});
test('effective config reads target-ref change policy through Core',async()=>{const text=JSON.stringify({schemaVersion:4,change:{requiredChecks:['build'],requiredApprovals:1}});const calls=[];const git={cwd:'/repo',run:async args=>{calls.push(args);if(args[0]==='ls-tree')return`100644 blob ${'b'.repeat(40)}\t.codex-safe.json\0`;if(args[0]==='show')return text;throw new Error(`unexpected ${args.join(' ')}`);}};const effective=await resolveEffectiveConfig(git,{requiredChecks:['lint'],requiredApprovals:0},'upstream/main');assert.deepEqual(effective.requiredChecks,['build','lint']);assert.equal(effective.requiredApprovals,1);assert.equal(effective.policySource,'committed+local-tightening');assert.match(effective.policyFingerprint,/^[0-9a-f]{64}$/);assert.deepEqual(calls[0],['ls-tree','-z','upstream/main','--','.codex-safe.json']);});
test('local explicit false remains false unless committed policy explicitly tightens it',()=>{const loose=mergePolicy({requireCleanWorktree:false,requirePushedHead:false,requireFreshTarget:false,blockOnReviewFindings:false},{});assert.equal(loose.requireCleanWorktree,false);assert.equal(loose.requirePushedHead,false);assert.equal(loose.requireFreshTarget,false);assert.equal(loose.blockOnReviewFindings,false);const tight=mergePolicy({requireCleanWorktree:false},{requireCleanWorktree:true,__present:true});assert.equal(tight.requireCleanWorktree,true);});
