'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const{runPreflight}=require('../src/preflight');
function fakeGit({status='',localTarget='targetsha'}={}){return{currentBranch:async()=> 'feat/x',revParse:async ref=>ref==='HEAD'?'headsha':localTarget,remoteUrl:async remote=>remote==='fork'?'git@github.com:me/r.git':'git@github.com:o/r.git',trackingRef:(r,b)=>`${r}/${b}`,mergeBase:async()=> 'base',commits:async()=>[{sha:'c1',subject:'feat: x'}],changedFiles:async()=>[{status:'M',path:'src/a.js'}],statusPorcelain:async()=>status,upstream:async()=> 'fork/feat/x',showFile:async()=>''};}
const config={sourceRemote:'fork',targetRemote:'upstream',targetBranch:'main',requireCleanWorktree:true,requirePushedHead:true,requireFreshTarget:true};
test('preflight is ready with fork topology when source and target snapshots agree',async()=>{const p=await runPreflight({git:fakeGit(),config,provider:{hasToken:true,getSourceBranchSha:async()=> 'headsha',getTargetBranchSha:async()=> 'targetsha'}});assert.equal(p.state,'READY');assert.equal(p.sourceRemote.owner,'me');assert.equal(p.targetRemote.owner,'o');});
test('preflight blocks dirty worktree and stale target',async()=>{const p=await runPreflight({git:fakeGit({status:' M x'}),config,provider:{hasToken:true,getSourceBranchSha:async()=> 'headsha',getTargetBranchSha:async()=> 'newtarget'}});assert.equal(p.state,'BLOCKED');assert.deepEqual(new Set(p.blockers.map(x=>x.code)),new Set(['dirty_worktree','target_ref_stale']));});
test('preflight treats remote aliases of the same repository/branch as source_is_target',async()=>{const git=fakeGit();git.remoteUrl=async()=> 'git@github.com:o/r.git';const p=await runPreflight({git,config:{...config,targetBranch:'feat/x'},provider:{kind:'github',hasToken:true,getSourceBranchSha:async()=> 'headsha',getTargetBranchSha:async()=> 'targetsha'}});assert.ok(p.blockers.some(x=>x.code==='source_is_target'));});
test('missing token blocks writes without making noisy provider API calls',async()=>{let calls=0;const p=await runPreflight({git:fakeGit(),config,provider:{kind:'github',hasToken:false,tokenEnvName:'GITHUB_TOKEN',validateCompatibility:async()=>{calls++;},getSourceBranchSha:async()=>{calls++;},getTargetBranchSha:async()=>{calls++;}}});assert.equal(calls,0);assert.ok(p.blockers.some(x=>x.code==='scm_credentials_missing'));});
test('plaintext HTTP API is explicitly visible in Delivery Preflight',async()=>{const p=await runPreflight({git:fakeGit(),config,provider:{kind:'gitlab',hasToken:true,client:{baseUrl:'http://192.168.10.20/api/v4'},getSourceBranchSha:async()=> 'headsha',getTargetBranchSha:async()=> 'targetsha'}});assert.equal(p.state,'READY_WITH_WARNINGS');assert.ok(p.warnings.some(x=>x.code==='scm_plaintext_http'));});
