'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const{assertApiBoundToRemote,githubApiBase,gitlabApiBase,normalizeRemoteForApi,tokenFromEnvironment,assertSameScmTopology}=require('../src/provider-factory');const{parseRemote}=require('../src/remote');const{assertSafeUrl,isPrivateIpLiteral}=require('../src/util');
test('SCM API token destination stays bound to remote or explicit machine alias',()=>{assert.equal(assertApiBoundToRemote('gitlab',{host:'gitlab.local',scheme:'ssh'},'https://gitlab.local/api/v4'),'https://gitlab.local/api/v4');assert.throws(()=>assertApiBoundToRemote('gitlab',{host:'gitlab.local',scheme:'ssh'},'https://evil.example/api/v4'),{code:'EAPIHOSTMISMATCH'});assert.equal(assertApiBoundToRemote('gitlab',{host:'gitlab.local',scheme:'ssh'},'https://10.0.0.8/api/v4',{'gitlab.local':['10.0.0.8']}),'https://10.0.0.8/api/v4');});
test('HTTPS remotes cannot downgrade API credentials to HTTP',()=>{const remote=parseRemote('https://gitlab.local/group/repo.git');assert.throws(()=>assertApiBoundToRemote('gitlab',remote,'http://gitlab.local/api/v4'),{code:'EAPITRANSPORTDOWNGRADE'});});
test('custom ports and relative roots are retained in API/project identity',()=>{const remote=parseRemote('https://scm.local:8443/gitlab/group/repo.git'),base=gitlabApiBase(remote,'https://scm.local:8443/gitlab/api/v4');assert.equal(base,'https://scm.local:8443/gitlab/api/v4');assert.equal(normalizeRemoteForApi(remote,base,'gitlab').projectPath,'group/repo');});
test('HTTP plus RFC1918 IP is allowed only after explicit opt-in',()=>{assert.equal(isPrivateIpLiteral('192.168.10.20'),true);assert.equal(assertSafeUrl('http://192.168.10.20/api/v4',true).origin,'http://192.168.10.20');assert.throws(()=>assertSafeUrl('http://192.168.10.20/api/v4',false),{code:'EINSECURESCM'});assert.equal(isPrivateIpLiteral('8.8.8.8'),false);assert.throws(()=>assertSafeUrl('http://8.8.8.8/api/v4',true),{code:'EPUBLICPLAINTEXTSCM'});});
test('HTTP source and target remotes on different ports are treated as different SCM origins',()=>{const source=parseRemote('http://192.168.10.20:8080/me/repo.git'),target=parseRemote('http://192.168.10.20:8081/org/repo.git');assert.throws(()=>assertSameScmTopology(source,target),{code:'ETOPOLOGYORIGIN'});});
test('GHES derives same-host API and explicit API paths are validated',()=>{assert.equal(githubApiBase({host:'ghe.local',scheme:'ssh'},'https://api.github.com'),'https://ghe.local/api/v3');assert.throws(()=>gitlabApiBase({host:'gl.local',scheme:'ssh'},'https://gl.local/not-v4'),{code:'EAPIBASE'});});
test('token environment variable names fail closed',()=>{assert.throws(()=>tokenFromEnvironment('BAD-NAME','GITLAB_TOKEN'),{code:'ETOKENENV'});});
