'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const{parseRemote}=require('../src/remote');const{probeOrigin,probeOrigins,looksLikeGitLab,looksLikeGitHubApi,resolveProviderConfig}=require('../src/provider-discovery');
function response(status,text){return{ok:status>=200&&status<300,status,headers:{get:()=>''},text:async()=>text};}
function networkError(code='ECONNREFUSED'){const error=new Error(code);error.code=code;throw error;}
test('custom HTTPS GitLab is discovered without sending credentials',async()=>{const calls=[];const fetchImpl=async(url,options)=>{calls.push({url:String(url),headers:options.headers});if(String(url).endsWith('/-/health'))return response(200,'GitLab OK');return response(404,'');};const remote=parseRemote('https://gitlab.lan:8443/group/repo.git');const r=await resolveProviderConfig(remote,{provider:'auto'},{fetchImpl});assert.equal(r.kind,'gitlab');assert.equal(r.config.gitlabApiBaseUrl,'https://gitlab.lan:8443/api/v4');assert.ok(calls.every(call=>!Object.keys(call.headers).some(k=>/token|authorization/i.test(k))));});
test('relative URL root is preserved during discovery',async()=>{const fetchImpl=async url=>String(url).includes('/gitlab/-/health')?response(200,'GitLab OK'):response(404,'');const remote=parseRemote('https://scm.lan/gitlab/group/repo.git');const r=await resolveProviderConfig(remote,{provider:'auto'},{fetchImpl});assert.equal(r.config.gitlabApiBaseUrl,'https://scm.lan/gitlab/api/v4');});
test('plain HTTP custom host is not probed unless explicitly allowed',()=>{const remote=parseRemote('http://192.168.10.20/group/repo.git');assert.equal(probeOrigin(remote,{allowInsecureHttp:false}),null);assert.equal(probeOrigin(remote,{allowInsecureHttp:true}),'http://192.168.10.20');});
test('SSH remote tries HTTPS first and HTTP only after explicit insecure opt-in',()=>{const remote=parseRemote('git@192.168.10.20:group/repo.git');assert.deepEqual(probeOrigins(remote,{allowInsecureHttp:false}),['https://192.168.10.20']);assert.deepEqual(probeOrigins(remote,{allowInsecureHttp:true}),['https://192.168.10.20','http://192.168.10.20']);});
test('SSH plus private IP discovers HTTP GitLab after HTTPS is unavailable',async()=>{const calls=[];const fetchImpl=async url=>{const value=String(url);calls.push(value);if(value.startsWith('https://'))return networkError();if(value==='http://192.168.10.20/-/health')return response(200,'GitLab OK');return response(404,'');};const remote=parseRemote('git@192.168.10.20:group/repo.git');const r=await resolveProviderConfig(remote,{provider:'auto',allowInsecureHttp:true},{fetchImpl});assert.equal(r.kind,'gitlab');assert.equal(r.config.gitlabApiBaseUrl,'http://192.168.10.20/api/v4');assert.ok(calls.some(value=>value.startsWith('https://')));assert.ok(calls.some(value=>value.startsWith('http://')));});
test('HTTPS wins when both HTTPS and HTTP expose the same provider',async()=>{const fetchImpl=async url=>String(url).endsWith('/-/health')?response(200,'GitLab OK'):response(404,'');const remote=parseRemote('git@192.168.10.20:group/repo.git');const r=await resolveProviderConfig(remote,{provider:'auto',allowInsecureHttp:true},{fetchImpl});assert.equal(r.config.gitlabApiBaseUrl,'https://192.168.10.20/api/v4');});
test('explicit GitLab can infer HTTP transport when health probe is allowlisted',async()=>{const fetchImpl=async url=>{const value=String(url);if(value.startsWith('https://'))return networkError();if(value.endsWith('/-/health'))return response(403,'Forbidden');return response(404,'');};const remote=parseRemote('git@192.168.10.20:group/repo.git');const r=await resolveProviderConfig(remote,{provider:'gitlab',allowInsecureHttp:true},{fetchImpl});assert.equal(r.kind,'gitlab');assert.equal(r.config.gitlabApiBaseUrl,'http://192.168.10.20/api/v4');assert.equal(r.discovery.mode,'explicit-provider-transport-probe');});
test('probe signatures are strict',()=>{assert.equal(looksLikeGitLab({ok:true,status:200,text:'GitLab OK'}),true);assert.equal(looksLikeGitLab({ok:true,status:200,text:'OK'}),false);assert.equal(looksLikeGitHubApi({ok:true,status:200,text:JSON.stringify({current_user_url:'x',repository_url:'y',rate_limit_url:'z'})}),true);});
