import os, re
from pathlib import Path
core=os.environ['CORE_SHA']; old_core=os.environ['OLD_CORE_SHA']
p=Path('package.json'); s=p.read_text().replace('"version": "4.1.1"','"version": "4.2.0"',1)
needle='''        "safeCodexPr.model": {\n          "type": "string",\n          "default": "",\n          "scope": "application",\n          "description": "%config.model%"\n        },\n'''
insert=needle+'''        "safeCodexPr.providerMode": { "type": "string", "enum": ["openai", "openai-compatible"], "default": "openai", "scope": "application", "description": "Codex provider runtime: built-in OpenAI or an explicitly configured OpenAI-compatible Responses endpoint." },\n        "safeCodexPr.providerBaseUrl": { "type": "string", "default": "", "scope": "application", "description": "HTTPS base URL for openai-compatible mode; user config.toml is intentionally ignored." },\n        "safeCodexPr.providerApiKeyEnv": { "type": "string", "default": "OPENAI_API_KEY", "scope": "application", "description": "Environment-variable name containing the provider API key; the secret value is never stored in settings." },\n        "safeCodexPr.connectTimeoutSeconds": { "type": "number", "default": 15, "minimum": 1, "maximum": 120, "scope": "application", "description": "Provider connection timeout in seconds." },\n        "safeCodexPr.requestTimeoutSeconds": { "type": "number", "default": 180, "minimum": 10, "maximum": 900, "scope": "application", "description": "Maximum time for one Codex request." },\n        "safeCodexPr.operationTimeoutSeconds": { "type": "number", "default": 300, "minimum": 30, "maximum": 1200, "scope": "application", "description": "Whole PR generation operation deadline." },\n        "safeCodexPr.streamIdleTimeoutSeconds": { "type": "number", "default": 60, "minimum": 5, "maximum": 600, "scope": "application", "description": "Maximum provider response-stream idle time." },\n'''
if '"safeCodexPr.providerMode"' not in s: s=s.replace(needle,insert,1)
s=re.sub(r',?\n\s*"safeCodexPr\.timeoutSeconds"\s*:\s*\{.*?\n\s*\}', '', s, count=1, flags=re.S); p.write_text(s)
p=Path('src/policy.js'); s=p.read_text(); anchor="  const profile = resolveReviewProfile(String(getUserOnlySetting(config, 'profile', 'standard') || 'standard'));\n"
runtime=anchor+'''  const providerMode = String(getUserOnlySetting(config,'providerMode','openai') || 'openai').trim();\n  const providerBaseUrl = String(getUserOnlySetting(config,'providerBaseUrl','') || '').trim();\n  const providerApiKeyEnv = String(getUserOnlySetting(config,'providerApiKeyEnv','OPENAI_API_KEY') || 'OPENAI_API_KEY').trim();\n  if (!['openai','openai-compatible'].includes(providerMode)) throw new Error('safeCodexPr.providerMode is invalid.');\n  if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(providerApiKeyEnv)) throw new Error('safeCodexPr.providerApiKeyEnv is invalid.');\n  const codexRuntime = Object.freeze({provider:Object.freeze({mode:providerMode,baseUrl:providerBaseUrl,apiKeyEnv:providerApiKeyEnv}),timeouts:Object.freeze({connectMs:clampNumber(getUserOnlySetting(config,'connectTimeoutSeconds',15),15,1,120,'connectTimeoutSeconds')*1000,requestMs:clampNumber(getUserOnlySetting(config,'requestTimeoutSeconds',180),180,10,900,'requestTimeoutSeconds')*1000,operationMs:clampNumber(project.timeoutSeconds ?? getUserOnlySetting(config,'operationTimeoutSeconds',300),300,30,1200,'operationTimeoutSeconds')*1000,idleMs:clampNumber(getUserOnlySetting(config,'streamIdleTimeoutSeconds',60),60,5,600,'streamIdleTimeoutSeconds')*1000})});\n'''
if 'const codexRuntime = Object.freeze' not in s: s=s.replace(anchor,runtime,1)
s=s.replace("    timeoutSeconds: clampNumber(project.timeoutSeconds ?? config.get('timeoutSeconds', 120), 120, 10, 300, 'timeoutSeconds'),\n","    codexRuntime,\n",1); p.write_text(s)
p=Path('src/codex.js'); s=p.read_text(); s=s.replace('const probeCodexCapabilities = sharedCodexCli.probeCodexCapabilities;\nconst withTemporaryDirectory','const probeCodexCapabilities = sharedCodexCli.probeCodexCapabilities;\nconst probeCodexRuntime = sharedCodexCli.probeCodexRuntime;\nconst withTemporaryDirectory',1); s=s.replace('    timeoutMs: options.timeoutSeconds * 1000,\n    schema:','    runtime: options.codexRuntime,\n    schema:',1); s=s.replace('  probeCodexCapabilities,\n  isCliCompatibilityError,','  probeCodexCapabilities,\n  probeCodexRuntime,\n  isCliCompatibilityError,',1); p.write_text(s)
p=Path('extension.js'); s=p.read_text(); s=s.replace("const { resolveCodexExecutable, probeCodexCapabilities, runCodex } = require('./src/codex');","const { resolveCodexExecutable, probeCodexCapabilities, probeCodexRuntime, runCodex } = require('./src/codex');",1)
old="""  const detected = await detectBase(root, options.baseBranch);
  const resolved = await resolveCodexExecutable(options.codexPath);
  await probeCodexCapabilities(resolved, options.model);
  vscode.window.showInformationMessage(ui(
    `Codex PR Safe 环境正常：${resolved.version}；当前分支 ${detected.branch}；Base ${detected.candidate || '需手动选择'}；CLI 能力已验证`,
    `Codex PR Safe environment OK: ${resolved.version}; branch ${detected.branch}; base ${detected.candidate || 'manual selection required'}; CLI capabilities verified`
  ));"""
new="""  const detected = await detectBase(root, options.baseBranch);
  const runtime = await probeCodexRuntime({codexPath:options.codexPath,model:options.model,runtime:options.codexRuntime});
  const endpoint = runtime.provider.endpointHost || 'Codex default';
  vscode.window.showInformationMessage(ui(
    `Codex PR Safe 环境正常：${runtime.codexVersion || options.codexPath}；当前分支 ${detected.branch}；Base ${detected.candidate || '需手动选择'}；Provider ${runtime.provider.mode} (${endpoint})；真实结构化探测 ${runtime.durationMs} ms`,
    `Codex PR Safe environment OK: ${runtime.codexVersion || options.codexPath}; branch ${detected.branch}; base ${detected.candidate || 'manual selection required'}; provider ${runtime.provider.mode} (${endpoint}); live structured probe ${runtime.durationMs} ms`
  ));"""; s=s.replace(old,new,1)
old="function showError(error) {\n  const detail = String(error?.stderr || error?.message || error || 'Unknown error').slice(0, 4000);"; new="function showError(error) {\n  const provider = error?.provider;\n  const meta = provider ? ` Provider: ${provider.mode}${provider.endpointHost ? ` @ ${provider.endpointHost}` : ''}.` : '';\n  const timing = Number.isFinite(error?.elapsedMs) ? ` Elapsed: ${Math.round(error.elapsedMs/100)/10}s.` : '';\n  const diagnostic = error?.diagnosticTail ? ` Diagnostic: ${String(error.diagnosticTail).slice(-1200)}` : '';\n  const detail = `${String(error?.message || error?.stderr || error || 'Unknown error')}${meta}${timing}${diagnostic}`.slice(0, 4000);"; s=s.replace(old,new,1); p.write_text(s)
for name,heading,text in [('README.md','## Codex provider runtime','Codex PR Safe intentionally ignores `~/.codex/config.toml`. Configure an OpenAI-compatible relay with `safeCodexPr.providerMode`, `providerBaseUrl`, and `providerApiKeyEnv`; compatible endpoints use Responses HTTP/SSE, and Environment Check performs a real structured round-trip.\n'),('README.zh-CN.md','## Codex Provider Runtime','Codex PR Safe 会主动忽略 `~/.codex/config.toml`。中转站通过 `safeCodexPr.providerMode`、`providerBaseUrl`、`providerApiKeyEnv` 显式配置；兼容端点固定走 Responses HTTP/SSE，环境检查会真实完成一次结构化 round-trip。\n')]:
 p=Path(name); x=p.read_text(); p.write_text(x if heading in x else x.rstrip()+f'\n\n{heading}\n\n{text}')
p=Path('CHANGELOG.md'); x=p.read_text(); entry='\n## 4.2.0 - 2026-08-28\n\n- Consume Core v4.6 Codex Runtime/Provider Contract with explicit OpenAI-compatible relay configuration, live Environment Check, HTTP/SSE relay transport, split runtime timeouts and provider-aware diagnostics.\n'; p.write_text(x if '## 4.2.0 - 2026-08-28' in x else x.replace('# Changelog\n','# Changelog\n'+entry,1))
for name in ['scripts/release.test.js','.codex-safe.example.json']:
 p=Path(name)
 if p.exists(): p.write_text(p.read_text().replace(old_core,core))
